flowchart LR
    U((사용자))
    U --> M1{로그인 유무}
    U --> M2[게시글 조회]

    M1 -->|비회원| L1[회원가입]
    M1 -->|비회원| L2[로그인]
    M1 -->|회원| MP[마이페이지]
    M1 -->|회원| PA[게시글 추가]

    MP --> MP1[회원 정보 수정]
    MP --> MP2[내 게시글 조회]
    MP --> MP3[나의 즐겨찾기 조회]

    M2 --> IF{회원이
    작성한 글인 경우}
    IF --> PI[게시글 수정]
    IF --> PD[게시글 삭제] 

    M2 --> LI[즐겨찾기 추가/삭제]
