flowchart LR
    U1((회원))
    U1 --> M1[마이페이지]
    U1 --> M2[게시글 추가]
    U1 --> M3[게시글 조회]
    M1 --> M1-1[회원정보수정]
    M1 --> M1-2[즐겨찾기 조회]
    M1 --> M1-3[내 게시글 조회]
    M1-3 --> M3-1[수정]
    M1-3 --> M3-2[삭제]
    M3 -->|회원인 경우| M3-3[즐겨찾기 등록/취소]

    U2((비회원))
    U2-->N1[회원가입]
    U2-->N2[로그인]
    U2-->M3