flowchart LR
    A((메인화면)) --> M1{로그인 유무}
    A --> M2[게시글 추가]
    A --> M3[게시글 조회]
    M1 -->|비회원| D1[회원가입]
    M1 -->|비회원| D2[로그인]
    M1 -->|회원| D3[마이페이지]

    M2 --> M2-1{로그인 유무}
    M2-1 -->|비회원| MD1[로그인 페이지 이동]
    M2-1 -->|회원| MD2-1[게시글 추가]
    

    M3 --> MY{회원이
    작성한 글인가요?}
    MY -->|회원| post_insert[게시글 수정]
    MY -->|회원| post_del[게시글 삭제] 
    post_del --> delete{정말 삭제할건가요?}
    delete --> |예|d(게시글 삭제)
    delete --> |아니요|d1(취소)

    M3 --> LI[즐겨찾기] --> L{로그인 유무}

    L -->|회원| q1{즐겨찾기 활성화가
    되어있나요?}
    q1-->|활성화|L1[즐겨찾기 추가]
    q1-->|비활성화|L2[즐겨찾기 해제]

    L -->|비회원| q2[로그인 페이지 이동]

    D2 --> ip{id, pw가 일치한가?}
    ip --> ip1-1(로그인 및 메인화면으로 이동)
    ip --> ip1-2(id 또는 pw가 맞지 않습니다.) --> D2

    D3 --> D3-3[회원 정보 수정]
    D3 --> D3-1[내 게시글 조회]
    D3 --> D3-2[나의 즐겨찾기 조회]